/**
  * Created by rdsel on 18/9/2016.
  *
  * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  * By starting with 1 and 2, the first 10 terms will be:
  * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  *
  */
object problem2 extends App {

  def sumFibonacci(threshold: Int): Int = {
    require(threshold > 0)
    def fibonacci(thre: Int, prev: Int, cur: Int): Int = {
      if(thre == 0) cur
      else fibonacci(thre -1, cur, prev + cur)
    }
    fibonacci(threshold, 0, 1)
  }

  // Numbers must be greater than 0
  val result = sumFibonacci(10)
  println(result)
}
